### PR TITLE
Added condition for hiding trend-line if we doesn't have enough points

### PR DESCRIPTION
**Pull request by tandrus**

### CODE REVIEW

**Comment by jaimedp** [comment]
This should be merged into the next release too @drosen0

**Comment by wglasshusain** [comment]
Hi Tandrus!  Thanks so much for the contribution.

Can I trouble you to please sign the Forio Contribution Agreement (FCA).  This keeps the code open source while providing joint copyright to you and to Forio.   We require it for merging in pull requests.   (We should have double checked on this before merging -- our apologies).   --> WIll, Forio open source coordinator.

**Comment by tandrus** [comment]
@wglasshusain 
Sorry, because I read message just now.
It's not a problem to agree FCA, but I don't know where.

**Comment by wglasshusain** [comment]
You can sign electronically here:   http://forio.com/contour/license.html

Thanks again for the contribution!

**Pull request merged**
