### PR TITLE
Remove lodash dependency

### PR DESCRIPTION
**Pull request by jaimedp**
Use ES5 array functions and custom functions to replace lodash dependency

### CODE REVIEW

**Comment by narenranjit** [comment]
- I think Object.assign is the only thing preventing IE11 compatibility, as far as I can tell. Isn't `nwt.merge` doing the same thing?
- Do we need nwt to be a global? Can we make it Contour.nwt if we need to?
- Tangentially, would it be a lot of work to get browserify into the build process? If we do we can also just require the specific lodash functions we need `var merge = require('lodash/merge')` instead of including the entire lodash bundle/ replicating relevant code locally (and also solve the global nwt issue)

**Comment by narenranjit** [comment]
Also `merge` also sorting is not very intuitive; maybe name it mergeAndSort? (I can't comment on that specific file directly because the diff is too large)

**Comment by breadbaker** [comment]
Love this

**Comment by jaimedp** [comment]
- I'll include a pollyfill for Object.assign and I think that should cover that part.
- As for the merge also sorting, I think you are refering to the `mergeArray` function? If that's the case, it was there before as `merge` and renamed it as `mergeArray`, I agree maybe clearer to name it `megeArrayAndSort`. The `merge` function should work the same as the lodash version (maybe some edge cases are not the same?)
- Yeah, there's no reason to have nwt in the global ns, except for the ease of wringing `nwt` instead of `Contour.nwt` everywhere :) (ie. `Contour.nwt.default(Contour.nwt.merge(Contour.nwt.omit(a, 'a'), Contour.merge(x, y))));`)
- As for doing browserify I was thinking that is the next step into cleaning the whole deployment and publishing system and use webpack or rollup and move to cjs based build as oppose to what we have now.

**Comment by narenranjit** [comment]
I think I was mixing up the 2 different merge functions - but isn't ` this._extraOptions.push(nwt.merge({}, defaults, extraPadding));` the equivalent of Object.assign anyway? Why do we need a polyfill?

**Comment by narenranjit** [comment]
re: `nwt` it'll practically just be a `var nwt = Contour.nwt` at the top of each file which needs it, which can then be replaced by a require whenever. But I'm fine if you want to merge this and move that to a different topic.

**Comment by jaimedp** [comment]
I added the Object.assign polyfill. As for using `nwt.merge` instead of Object.assign, some times I think we actually want to not do a deep clone which is what `merge` does, so that's why we need Object.assign... 

As for the nwt on the global namespace, I think we can address this when we move to cjs modules, I started to make the changes to add it to the Contour object and it gets a bit complicated due to the circular dependencies it generates in our current build setup.

**Pull request merged**
