### PR TITLE
yAxis:tickValues receive function

### PR DESCRIPTION
**Pull request by parikhshiv**
For issue #252 - allow user to pass in function to yAxis:tickValues parameter. See the following jsfiddle for usage - http://jsfiddle.net/a5L7x0c5/6/.

### CODE REVIEW

**Comment by narenranjit** [comment]
This only runs the function on initialization -- so if you ever call setData again you're basically stuck since you're basically stuck since there'll be no way to change the original values (for e.g. http://jsfiddle.net/a5L7x0c5/7)

The problem is worse if don't see initial data (http://jsfiddle.net/a5L7x0c5/8) -- in this case you'll never get tickvalues.

If we make this a function it'll need to be called at every render to be useful. What do you think?

**Comment by drosen0** [comment]
The example in the fiddle can be done without a callback. Do you have an example use case for this that you couldn't do previously?

**Comment by narenranjit** [comment]
@drosen0 which fiddle? (and hi!)

**Comment by drosen0** [comment]
Hi @narenranjit and @parikhshiv! I could see making `tickValues` a callback if there were something about the data that could only be inferred at render-time. See these fiddles:

* http://jsfiddle.net/5csjbzLx/1/
* http://jsfiddle.net/f6k327sm/1/

**Comment by jaimedp** [comment]
FYI I'm exploring a setup where any parameter in the config object can be a function and will be invoked just before rendering.

**Comment by narenranjit** [comment]
Closing in favor of a more general solution.

**Pull request closed without merging**
