### PR TITLE
Detach nw utilities from _

### PR DESCRIPTION
**Pull request by breadbaker**
Contour relies on lodash being on the global namespace which it then alters to add utility functions.  Requiring lodash in other app modules would reset lodash breaking future instances of Contour.  Found that putting utilitities in own namespace nw resolves this issue.  

**Future** We should still consider:
- not relying on libraries in global space.
- registering forio-contour with npm

### CODE REVIEW

**Comment by narenranjit** [comment]
Thanks for this Dan! Will take a look and merge later next week.

**Comment by drosen0** [comment]
Thanks for this. FYI, some projects are dependent on utilities in `_.nw`.

**Comment by breadbaker** [comment]
What projects?  If you really want to extend _ with nw why not extend the library and make _ an internal dependency?  Otherwise it seems like it might be better to put nw on its own.

**Comment by parikhshiv** [comment]
Hi @breadbaker - appreciate the PR. 

I'm a little curious as to why we need to set nw as a global variable on the window here - can you explain your thought process, and could this be accomplished without setting an additional global variable?

**Comment by drosen0** [comment]
I agree with @parikhshiv's https://github.com/forio/contour/pull/237#issuecomment-268656463 about polluting the global namespace. Ideally we'd reduce access to `nw` at the same time as detaching it from `_`.

A couple ideas:

* Attach it to `Contour` as `Contour.nw`.
* Use binding context, ie. make it available on the prototype. This would keep `nw` totally private.

Note that some visualizations use `_.nw`, so those would need to be changed. If I remember correctly, at least one sim uses `_.nw`, and I don't remember which.

**Comment by breadbaker** [comment]
Contour.NW is a great solution!

**Comment by breadbaker** [comment]
Contour is not defined until well after all of the _.nw helpers are defined.

**Pull request closed without merging**
