### PR TITLE
add nw-vertical-track to all comparing point to x-axis

### PR DESCRIPTION
**Pull request by breadbaker**
screen shot 2017-11-08 at 9 49 27 am

### CODE REVIEW

**Comment by jaimedp** [comment]
Hi Dan!

Any reason not to do this as a separate visualization instead of inside tooltip? The general principle was to keep the visualizations small and simple so you can compose them to achieve what you want. I remember having this specific visualization somewhere as as stand alone :)

**Comment by breadbaker** [comment]
Do you by chance remember which one that was?  I agree that by name I would not expect the tooltip to necessarily have this functionality.  Although in implementation I was struggling to attach multiple listeners to the `circle` elements.

**Comment by narenranjit** [comment]
@breadbaker Is this http://jsfiddle.net/zecmfgj7/7/ similar to what you're looking for?

**Comment by narenranjit** [comment]
Closing this, Dan comment here if there are things this PR makes possible which isn't shown in the jsfiddle example.

**Pull request closed without merging**
